"""create links table

Revision ID: 0001
Revises:
Create Date: 2026-08-07

Hand-written rather than autogenerated, because the first migration is the one
worth reading carefully — and because autogenerate has no opinion about index
names, which end up in error messages and are worth choosing deliberately.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "links",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("target_url", sa.String(length=2048), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("hit_count", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("last_hit_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_links"),
    )
    # Unique index rather than a plain one: it enforces the constraint *and*
    # serves the redirect lookup. One index doing both jobs is one less thing
    # to keep in sync.
    op.create_index("ux_links_code", "links", ["code"], unique=True)


def downgrade() -> None:
    op.drop_index("ux_links_code", table_name="links")
    op.drop_table("links")
